import os
os.system ('clear')
os.system ('clear')                                                                                  
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet HK instagram')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤ مﺴإ  \033[1;33m: the_king_of06")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m: zouhairettaher2006@gmail.com")
print ("")
print ("")
print (" \033[1;32mﺮﺴㅤﺔﻤﻠڪ :\033[1;33m Hhh.wwadima.wdad1082")
print ("")
print ("")
os.system ('figlet')

